name: Build and Publish ZIP to gh-pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release /p:Version=${{ steps.gitversion.outputs.semVer }}
      - name: Publish project
        run: dotnet publish -c Release -o publish /p:Version=${{ steps.gitversion.outputs.semVer }}

      - name: Create ZIP
        run: powershell Compress-Archive -Path publish\* -DestinationPath $env:RUNNER_TEMP\publish.zip -Force

      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy publish.zip to gh-pages
        run: copy $env:RUNNER_TEMP\publish.zip publish.zip

      - name: Commit and push publish.zip
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add publish.zip
          git commit -m "Update publish.zip" || echo "No changes to commit"
          git push
