name: Generate Version File

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # lub wersja, której potrzebujesz
      - name: Diagnostyka .NET
        run: |
          dotnet --info
          dotnet tool list --global
      - name: Install GitVersion
        run: |
          dotnet tool install --global GitVersion.Tool || { echo "❌ Instalacja GitVersion się nie powiodła"; exit 1; }
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH


      - name: Check if GitVersion is installed
        run: |
          export PATH="$PATH:$HOME/.dotnet/tools"
          which gitversion
          gitversion --version

      - name: Generate version.txt
        run: |
          export PATH="$PATH:$HOME/.dotnet/tools"
          gitversion /showvariable SemVer > version.txt

      - name: Commit and push version.txt if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add version.txt
          if ! git diff --cached --quiet; then
            git commit -m "Update version.txt [skip ci]"
            git push
          else
            echo "No changes in version.txt"
          fi

      - name: Upload version.txt as artifact
        uses: actions/upload-artifact@v4
        with:
          name: version.txt
          path: version.txt
