name: Update Version on Netlify

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main repo
      uses: actions/checkout@v3

    - name: Install GitVersion
      run: dotnet tool install --global GitVersion.Tool

    - name: Generate version.txt
      run: |
        export PATH="$PATH:$HOME/.dotnet/tools"
        gitversion /showvariable SemVer > version.txt

    - name: Checkout Netlify repo
      uses: actions/checkout@v3
      with:
        repository: https://majestic-axolotl-224ec3.netlify.app  # podmień na repo Netlify
        path: netlify-site

    - name: Copy version.txt to Netlify repo
      run: |
        cp version.txt netlify-site/version.txt

    - name: Commit and push changes to Netlify repo
      run: |
        cd netlify-site
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add version.txt
        git commit -m "Update version.txt to $(cat ../version.txt)" || echo "No changes to commit"
        git push origin main
      env:
        # Token z uprawnieniami do push do repo Netlify
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
