name: Generate Version File

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Run GitVersion
        uses: GitTools/actions/gitversion/execute@v0.11.0
        id: gitversion

      - name: Save SemVer to version.txt
        run: echo "${{ steps.gitversion.outputs.semver }}" > version.txt

