name: Generate Version File

on:
  push:
    branches:
      - main

jobs:
  generate-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Run GitVersion
        uses: gittools/actions/gitversion/execute@v0.10.5
        id: gitversion

      - name: Save version to version.txt
        run: echo "${{ steps.gitversion.outputs.semVer }}" > version.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update version.txt"
          title: "Update version.txt to ${{ steps.gitversion.outputs.semVer }}"
          body: "Automatic version update"
          branch: "update-version-${{ steps.gitversion.outputs.semVer }}"
          delete-branch: true

      - name: Upload version.txt as artifact
        uses: actions/upload-artifact@v4
        with:
          name: version.txt
          path: version.txt