name: Generate and Update version.txt

on:
  push:
    branches:
      - main

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install GitVersion
      run: dotnet tool install --global GitVersion.Tool

    - name: Generate version.txt
      run: |
        export PATH="$PATH:$HOME/.dotnet/tools"
        gitversion /showvariable SemVer > version.txt

    - name: Commit and push version.txt if changed
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add version.txt
        git diff --cached --quiet || (git commit -m "Update version.txt to $(cat version.txt)" && git push)
